site_name: PowerXaaS
site_url: https://github.com/otabut/PowerXaaS
site_description: Powershell module for exposing features "as a Service" through a HTTP server
site_author: otabut
repo_url: https://github.com/otabut/PowerXaaS


pages:
  - Home: index.md
  - Setup: setup.md
  - Features and Endpoints: features-and-endpoints.md
  - Custom features scripts: custom-features-scripts.md
  - Authentication with JSON web tokens: json-web-tokens.md
  - HTTP server commands: http-server-commands.md
  - Credits: credits.md
